version: '3.8'

services:
  galenos-mini-front:
    build:
      context: .
      dockerfile: Dockerfile.galenos-mini-front
    depends_on:
      migration:
        condition: service_started
    volumes:
      - .:/galenos_mini_front
    networks:
      - app-tier
    ports:
      - "8000:8000"
    command: sh -c "python /galenos_mini_front/galenos_mini_front/manage.py runserver 0:8000"
    restart: always

  migration:
    build:
      context: .
      dockerfile: Dockerfile.galenos-mini-front
    volumes:
      - .:/galenos_mini_front
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - app-tier
    command: sh -c "python /galenos_mini_front/galenos_mini_front/manage.py makemigrations && python /galenos_mini_front/galenos_mini_front/manage.py migrate"
    restart: always


networks:
  app-tier:
    driver: bridge