FROM python:3.10-alpine
RUN apk add --no-cache bash
WORKDIR /galenos_mini_front
COPY galenos_mini_front/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 8000
COPY galenos_mini_front galenos_mini_front