# Generated by Django 4.2.7 on 2023-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("medico_id", models.IntegerField()),
                ("monto", models.IntegerField()),
                ("tipo_pago", models.CharField(max_length=255)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
